name: Testing compiling slugs

on: [push]

env:
  BUILD_TYPE: Release
  CCACHE_VERSION: 4.2.1

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", 
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }


    steps:
      # SRC: https://stackoverflow.com/questions/67457510/git-submodule-update-remote-merge-yields-fatal-needed-a-single-revision
    - uses: actions/checkout@main
      with:
         # we need the submodules.
         submodules: recursive
    - name: Update submodule.
      run: git submodule update --remote
    - name: Install various packages needed 
      run: sudo apt-get install build-essential libboost-all-dev
    - name: Make the slugs executable
      run: cd src; make
    - name: Test a simple slugs run
      run: time src/slugs examples/firefighting.slugsin

